directory:
  submit: ./Submit
  output: ./Output
  done: ./Done
  error: ./ERROR
  src_path: ./src
  pot_path_gga: /data/vasp4us/pot/PBE52
  pot_path_lda: /data/vasp4us/pot/LDA52

program:
  vasp_std: /data/vasp4us/vasp_std
  vasp_gam: /data/vasp4us/vasp_gam
  vasp_ncl: /data/vasp4us/vasp_ncl
  gnuplot: /gnuplot
  mpi_command: mpirun

calculation:
  magnetic_ordering: T
  band: T
  density_of_states: T
  hse_oneshot: T
  dielectric: T
  effective_mass: T
  potential_type: GGA

cif2vasp:
  pot_name:
    GGA:
    LDA: 
  soc_target:
  u_value:

vasp_parallel:
  npar: 2
  kpar: 2

hybrid_oneshot:
  alpha: 0.25
  cutoff_df_dvb: 0.3
  band_structure_correction: True

effective_mass:
  carrier_type:
    - hole
    - electron

magnetic_ordering:
  minimum_moment: 0.5

