directory:
  submit: ./Submit                      # a path of structure file or a directory containg structure files
  output: ./Output                      # a path of a directory where calculation is conducted
  done: ./Done                          # a path of a directory where results are saved
  error: ./ERROR                        # a path of a directory where the materials with error are saved
  src_path: ./src                       # a path of the directory of AMP2 source codes
  pot_path_gga: /data/vasp4us/pot/PBE52 # a path of directory for GGA pseudopotential
  pot_path_lda: /data/vasp4us/pot/LDA52 # a path of directory for GGA pseudopotential

program:
  vasp_std: /data/vasp4us/vasp_std      # a path of standard version of VASP
  vasp_gam: /data/vasp4us/vasp_gam      # a path of gamma-only version of VASP
  vasp_ncl: /data/vasp4us/vasp_ncl      # a path of noncollinear version of VASP
  gnuplot: /gnuplot                     # a path of executable file for gnuplot
  mpi_command: mpirun                   # mpi command (ex. mpirun, mpiexec, ...)

calculation:
  magnetic_ordering: T                  # On/Off for the calculation to idetify most stable magnetic spin ordering
  band: T                               # On/Off for the calculation for band structure and band gap
  density_of_states: T                  # On/Off for the calculation for density of states
  hse_oneshot: T                        # On/Off for the calculation for HSE@PBE
  dielectric: T                         # On/Off for the calculation for dielectric constant
  effective_mass: T                     # On/Off for the calculation for effective mass
  potential_type: GGA                   # calculation scheme (LDA or GGA)

vasp_parallel:
  npar: 2                               # the number of bands that are treated in parallel. It is same to NPAR tag in VASP.
  kpar: 2                               # the number of kpoints that are treated in parallel. It is same to NPAR tag in VASP.

cif2vasp:
  pot_name:                             # the pseudopotential potential for element.
    GGA:                                # (Ex. GGA:\n    Ge:Ge_d\n    Cu:Cu_pv) 
    LDA: 
  soc_target:                           # the elements to carry out spin-orbit coupling calculation (Ex. soc_target:\n    - Bi\n    -Pb)
  u_value:                              # U values for PBE+U calculation (Ex. u_value:\n    La: 7.5\n    Ce: 8.5)

hybrid_oneshot:
  alpha: 0.25                           # a mixing parameter for hybrid calculation. If "Auto" is set, the mixing parameter is set to be one of permittivity and PBE0 calualation is performed.
  cutoff_df_dvb: 0.3                    # DF/DVB used to classify semiconductor candidates. (See paper)
  band_structure_correction: True       # On/Off for the band structure correction

effective_mass:
  carrier_type:                         # carrier type of effective mass to be estimated
    - hole
    - electron

