directory:
  submit: ./POSCAR_NiO           
  output: ./Output                     
  done: ./Done                         
  error: ./ERROR                       
  src_path: ./src                      
  pot_path_gga: /data/vasp4us/pot/PBE52
  pot_path_lda: /data/vasp4us/pot/LDA52

program:
  vasp_std: /data/vasp4us/vasp_std     
  vasp_gam: /data/vasp4us/vasp_gam     
  vasp_ncl: /data/vasp4us/vasp_ncl     
  gnuplot: /gnuplot                    
  mpi_command: mpirun                  

vasp_parallel:
  npar: 2                              
  kpar: 2                              

calculation:
  magnetic_ordering: T
  band: T
  density_of_states: T
  hse_oneshot: T
  dielectric: F
  effective_mass: F
